Repository ergebnis/php-cs-fixer-config, pull requests merged in 2020-12, with the labels that each got.

#255 Enhancement: Update friendsofphp/php-cs-fixer
  composer.json
  composer.lock
  phpstan-baseline.neon
  psalm-baseline.xml
  src/RuleSet/Laravel6.php
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Laravel6Test.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#256 Fix: Update CHANGELOG.md
  CHANGELOG.md
Labels: bug, merge

#257 Enhancement: Configure phpdoc_order_by_value fixer to order dataProvider annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#258 Enhancement: Configure phpdoc_order_by_value fixer to order uses annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#259 Enhancement: Configure phpdoc_order_by_value fixer to order author annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#260 Enhancement: Configure phpdoc_order_by_value fixer to order coversNothing annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#261 Enhancement: Configure phpdoc_order_by_value fixer to order depends annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#262 Enhancement: Configure phpdoc_order_by_value fixer to order group annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#263 Enhancement: Configure phpdoc_order_by_value fixer to order internal annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#264 Enhancement: Configure phpdoc_order_by_value fixer to order requires annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#265 Allow installations on PHP8
  .github/settings.yml
  .github/workflows/integrate.yaml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: enhancement

#266 Fix: Do not use deprecated RuleSet
  phpstan-baseline.neon
  psalm-baseline.xml
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#267 Fix: Sort fixers
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#268 Fix: Rename methods and variables
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#269 Fix: Comment
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#270 Fix: Rename variables
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#271 Fix: Remove unnecessary sort
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#272 Fix: Rename variable
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#273 Fix: Diff
  src/RuleSet/Laravel6.php
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
  test/Unit/RuleSet/Laravel6Test.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: bug, merge

#274 Enhancement: Update ergebnis/composer-normalize
  composer.json
  composer.lock
Labels: enhancement, merge

#275 Enhancement: Update ergebnis/test-util
  composer.json
  composer.lock
Labels: enhancement, merge

#276 Fix: Update friendsofphp/php-cs-fixer
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, merge

#277 Fix: Update phpstan/phpstan
  composer.json
  composer.lock
Labels: bug, dependency, merge

#278 Fix: Update phpunit/phpunit
  composer.json
  composer.lock
Labels: bug, dependency, merge

#279 Enhancement: Enable array_push fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#280 Enhancement: Enable clean_namespace fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#281 Enhancement: Enable lambda_not_used_import fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#282 Enhancement: Enable no_alias_language_construct_call fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#283 Enhancement: Enable no_trailing_whitespace_in_string fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#284 Enhancement: Enable no_useless_sprintf fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#285 Enhancement: Enable and configure operator_linebreak fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#286 Enhancement: Enable and configure phpdoc_inline_tag_normalizer fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#287 Enhancement: Enable and configure phpdoc_tag_casing fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#288 Enhancement: Enable regular_callable_call fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#289 Enhancement: Enable and configure single_space_after_construct fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#290 Enhancement: Enable switch_continue_to_break fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#291 Enhancement: Enable ternary_to_elvis_operator fixer
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#292 Fix: Test
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#293 Enhancement: Synchronize with ergebnis/php-cs-fixer-config-template
  test/Double/Config/RuleSet/DummyRuleSet.php
  test/Unit/FactoryTest.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: enhancement, merge

#294 Enhancement: Synchronize with ergebnis/php-cs-fixer-config-template
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: enhancement, merge

#296 Enhancement: Synchronize with ergebnis/php-cs-fixer-config-template
  .github/dependabot.yaml
  psalm.xml
  test/Unit/phpunit.xml
Labels: enhancement, merge

#295 Make assert equals strict
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: enhancement

#300 Enhancement: Add rule set for PHPUnit
  CHANGELOG.md
  README.md
  src/RuleSet/PhpUnit.php
  test/Unit/RuleSet/PhpUnitTest.php
Labels: enhancement, merge

#301 Enhancement: Enable and configure php_unit_test_case_static_method_calls fixer
  CHANGELOG.md
  src/RuleSet/PhpUnit.php
  test/Unit/RuleSet/PhpUnitTest.php
Labels: enhancement, merge

#303 Enhancement: Enable php_unit_set_up_tear_down_visibility fixer
  CHANGELOG.md
  src/RuleSet/PhpUnit.php
  test/Unit/RuleSet/PhpUnitTest.php
Labels: enhancement, merge

#305 Fix: Reference
  CHANGELOG.md
Labels: bug, merge

#306 Enhancement: Configure braces fixer to allow single-line anonymous classes with empty body
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#302 Enhancement: Configure phpdoc_order_by_value fixer to order throws annotations
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#310 Enhancement: Configure phpdoc_order_by_value fixer to order throws annotations
  CHANGELOG.md
  src/RuleSet/PhpUnit.php
  test/Unit/RuleSet/PhpUnitTest.php
Labels: enhancement, merge

#311 Enhancement: Add ExplicitRuleSet marker interface
  CHANGELOG.md
  phpstan-baseline.neon
  src/RuleSet/ExplicitRuleSet.php
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#312 Enhancement: Extract ExplicitRuleSetTestCase
  phpstan-baseline.neon
  phpstan.neon
  test/Unit/RuleSet/ExplicitRuleSetTestCase.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: enhancement, merge

#313 Enhancement: Require ExplicitRuleSets only not to configure rule sets
  CHANGELOG.md
  src/RuleSet/ExplicitRuleSet.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
  test/Unit/RuleSet/ExplicitRuleSetTestCase.php
Labels: enhancement, merge

#314 Fix: Configure configurable fixers in implementations of ExplicitRuleSet explicitly
  CHANGELOG.md
  src/RuleSet/ExplicitRuleSet.php
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
  test/Unit/RuleSet/ExplicitRuleSetTestCase.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: bug, merge

#315 Fix: Do not use constants
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: bug, merge

#316 Fix: Use assertSame() instead of assertEquals()
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: bug, merge

#317 Enhancement: Assert that configuration items are sorted by key
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: enhancement, merge

#318 Enhancement: Assert that rules and configuration options are sorted recursively
  phpstan-baseline.neon
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
Labels: enhancement, merge

#319 Fix: Do not configure rules using deprecated configuration options
  CHANGELOG.md
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  src/RuleSet/PhpUnit.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
  test/Unit/RuleSet/ExplicitRuleSetTestCase.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
  test/Unit/RuleSet/PhpUnitTest.php
Labels: bug, merge

#320 Fix: Configure rules in implementations of ExplicitRuleSet using every non-deprecated configuration option
  CHANGELOG.md
  phpstan-baseline.neon
  psalm-baseline.xml
  src/RuleSet/Php71.php
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
  test/Unit/RuleSet/ExplicitRuleSetTestCase.php
  test/Unit/RuleSet/Php71Test.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
Labels: bug, merge

#321 Fix: Only require implementations of ExplicitRuleSet to configure every non-deprecated rule
  CHANGELOG.md
  src/RuleSet/ExplicitRuleSet.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
  test/Unit/RuleSet/ExplicitRuleSetTestCase.php
Labels: bug, merge

#322 Enhancement: Synchronize rule set for PhpUnit with phpunit/phpunit
  src/RuleSet/PhpUnit.php
  test/Unit/RuleSet/PhpUnitTest.php
Labels: enhancement, merge

#323 Enhancement: Add rule set for fakerphp/faker
  CHANGELOG.md
  README.md
  src/RuleSet/Faker.php
  test/Unit/RuleSet/FakerTest.php
Labels: enhancement, merge
