Repository ergebnis/php-cs-fixer-config, pull requests merged in 2021-05, with the labels that each got.

#402 Fix: Remove jangregor/phpstan-prophecy
  composer.json
  composer.lock
Labels: bug, merge

#403 Enhancement: Configure trailing_comma_in_multiline fixer to add trailing commas for arguments
  CHANGELOG.md
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  src/RuleSet/Php80.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
  test/Unit/RuleSet/Php80Test.php
Labels: enhancement, merge

#404 Enhancement: Configure trailing_comma_in_multiline fixer to add trailing commas for parameters
  CHANGELOG.md
  src/RuleSet/Php80.php
  test/Unit/RuleSet/Php80Test.php
Labels: enhancement, merge

#405 Fix: Reference
  CHANGELOG.md
Labels: bug, merge

#406 Enhancement: Enable and configure phpdoc_to_property_type fixer
  CHANGELOG.md
  src/RuleSet/Php74.php
  src/RuleSet/Php80.php
  test/Unit/RuleSet/Php74Test.php
  test/Unit/RuleSet/Php80Test.php
Labels: enhancement, merge

#407 Fix: Drop support for PHP 7.2
  .github/settings.yml
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
Labels: bug, merge

#408 Enhancement: Use Php73 rule set
  .php-cs-fixer.php
  src/Factory.php
  test/AutoReview/SrcCodeTest.php
  test/Unit/FactoryTest.php
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
  test/Unit/RuleSet/ExplicitRuleSetTestCase.php
Labels: enhancement, merge

#409 Fix: Remove Php71 rule set
  CHANGELOG.md
  README.md
  src/RuleSet/Php71.php
  test/Unit/RuleSet/Php71Test.php
Labels: bug, merge

#410 Fix: Remove Php72 rule set
  CHANGELOG.md
  README.md
  src/RuleSet/Php72.php
  test/Unit/RuleSet/Php72Test.php
Labels: bug, merge

#413 Fix: Remove Laravel6 rule set
  CHANGELOG.md
  README.md
  src/RuleSet/Laravel6.php
  test/Unit/RuleSet/Laravel6Test.php
Labels: bug, merge

#415 Fix: Remove Faker rule set
  CHANGELOG.md
  README.md
  src/RuleSet/Faker.php
  test/Unit/RuleSet/FakerTest.php
Labels: bug, merge

#414 Fix: Collect code coverage with Xdebug
  .github/workflows/integrate.yaml
Labels: bug, merge

#416 Fix: Remove PhpUnit rule set
  CHANGELOG.md
  README.md
  src/RuleSet/PhpUnit.php
  test/Unit/RuleSet/PhpUnitTest.php
Labels: bug, merge

#417 Fix: Configure infection/infection via infection.json
  .github/workflows/integrate.yaml
  Makefile
  infection.json
Labels: bug, merge

#418 Fix: Remove infection/infection
  .gitattributes
  .github/CONTRIBUTING.md
  .github/settings.yml
  .github/workflows/integrate.yaml
  Makefile
  composer.json
  composer.lock
  infection.json
Labels: bug, merge

#419 Fix: Migrate configuration for phpunit/phpunit
  test/Unit/phpunit.xml
Labels: bug, merge

#420 Enhancement: Update friendsofphp/php-cs-fixer
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
  CHANGELOG.md
  Makefile
  README.md
  composer.json
  composer.lock
  test/Unit/RuleSet/AbstractRuleSetTestCase.php
  test/Unit/RuleSet/ExplicitRuleSetTestCase.php
Labels: enhancement

#421 Enhancement: Configure function_to_constant fixer to include get_called_class()
  CHANGELOG.md
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  src/RuleSet/Php80.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
  test/Unit/RuleSet/Php80Test.php
Labels: enhancement, merge

#422 Enhancement: Configure phpdoc_align fixer to include method and property annotations
  CHANGELOG.md
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  src/RuleSet/Php80.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
  test/Unit/RuleSet/Php80Test.php
Labels: enhancement, merge

#423 Fix: Add missing word
  CHANGELOG.md
Labels: bug, merge

#424 Enhancement: Configure phpdoc_scalar fixer to include callback
  CHANGELOG.md
  src/RuleSet/Php73.php
  src/RuleSet/Php74.php
  src/RuleSet/Php80.php
  test/Unit/RuleSet/Php73Test.php
  test/Unit/RuleSet/Php74Test.php
  test/Unit/RuleSet/Php80Test.php
Labels: enhancement, merge

#425 Fix: Update CHANGELOG.md
  CHANGELOG.md
Labels: bug, merge

#428 Fix: Wrong type
  CHANGELOG.md
  src/RuleSet/Php74.php
  src/RuleSet/Php80.php
  test/Unit/RuleSet/Php74Test.php
  test/Unit/RuleSet/Php80Test.php
Labels: bug, merge
